#pragma once
#include "../include.h"
namespace esp {
	void runESP();
    inline static std::map<int, std::string> weaponMap = {
    {1, "DEAGLE"},
    {2, "BERETTAS"},
    {3, "FIVESEVEN"},
    {4, "GLOCK"},
    {7, "AK47"},
    {8, "AUG"},
    {9, "AWP"},
    {10, "FAMAS"},
    {11, "G3SG1"},
    {13, "GALIL"},
    {14, "M249"},
    {16, "M4A1"},
    {17, "MAC10"},
    {19, "P90"},
    {23, "MP5SD"},
    {24, "UMP45"},
    {25, "XM1014"},
    {26, "BIZON"},
    {27, "MAG7"},
    {28, "NEGEV"},
    {29, "SAWEDOFF"},
    {30, "TEC9"},
    {31, "TASER"},
    {32, "P2000"},
    {33, "MP7"},
    {34, "MP9"},
    {35, "NOVA"},
    {36, "P250"},
    {37, "SHIELD"},
    {38, "SCAR20"},
    {39, "SG556"},
    {40, "SSG08"},
    {41, "KNIFEGG"},
    {42, "CT KNIFE"},
    {43, "FLASHBANG"},
    {44, "HE"},
    {45, "SMOKE"},
    {46, "MOLOTOV"},
    {47, "DECOY"},
    {48, "INCENDIARY"},
    {49, "C4"},
    {57, "HEALTHSHOT"},
    {59, "T KNIFE"},
    {60, "M4A1-S"},
    {61, "USP-S"},
    {63, "CZ75A"},
    {64, "REVOLVER"},
    {68, "TAGRENADE"},
    {69, "FISTS"},
    {70, "BREACHCHARGE"},
    {72, "TABLET"},
    {74, "MELEE"},
    {75, "AXE"},
    {76, "HAMMER"},
    {78, "SPANNER"},
    {80, "GHOST"},
    {81, "FIREBOMB"},
    {82, "DIVERSION"},
    {83, "FRAG GRENADE"},
    {84, "SNOWBALL"},
    {85, "BUMPMINE"},
    {500, "BAYONET"},
    {503, "CSS"},
    {505, "FLIP"},
    {506, "GUT"},
    {507, "KARAMBIT"},
    {508, "M9 BAYONET"},
    {509, "TACTICAL"},
    {512, "FALCHION"},
    {514, "BOWIE"},
    {515, "BUTTERFLY"},
    {516, "PUSH"},
    {517, "CORD"},
    {518, "CANIS"},
    {519, "URSUS"},
    {520, "GYPSY JACKKNIFE"},
    {521, "OUTDOOR"},
    {522, "STILETTO"},
    {523, "WIDOWMAKER"},
    {525, "SKELETON"},
    {526, "KUKRI"},
    {5027, "BLOODHOUND GLOVES"},
    {5028, "T GLOVES"},
    {5029, "CT GLOVES"},
    {5030, "SPORTY GLOVES"},
    {5031, "SLICK GLOVES"},
    {5032, "LEATHER HANDWRAPS"},
    {5033, "MOTORCYCLE GLOVES"},
    {5034, "SPECIALIST GLOVES"},
    {5035, "HYDRA GLOVES"}
    };

    inline std::map<std::string, int> boneMap = {
        {"head", 6},
        {"neck_0", 5},
        {"spine_1", 4},
        {"spine_2", 2},
        {"pelvis", 0},
        {"arm_upper_L", 8},
        {"arm_lower_L", 9},
        {"hand_L", 10},
        {"arm_upper_R", 13},
        {"arm_lower_R", 14},
        {"hand_R", 15},
        {"leg_upper_L", 22},
        {"leg_lower_L", 23},
        {"ankle_L", 24},
        {"leg_upper_R", 25},
        {"leg_lower_R", 26},
        {"ankle_R", 27}
    };
    inline std::map<std::string, int> boneMap2 = {
        {"Head", 6},
        {"Neck", 5},
        {"Spine", 2},
        {"Pelvis", 0},
        {"Left Arm", 9},
        {"Left Hand", 10},
        {"Right Arm", 14},
        {"Right Hand", 15},
        {"Left Leg", 23},
        {"Right Leg", 26},
    };

    inline std::vector<std::pair<std::string, std::string>> boneConnections = {
                        {"head", "neck_0"},
                        {"neck_0", "spine_1"},
                        {"spine_1", "spine_2"},
                        {"spine_2", "pelvis"},
                        {"spine_1", "arm_upper_L"},
                        {"arm_upper_L", "arm_lower_L"},
                        {"arm_lower_L", "hand_L"},
                        {"spine_1", "arm_upper_R"},
                        {"arm_upper_R", "arm_lower_R"},
                        {"arm_lower_R", "hand_R"},
                        {"pelvis", "leg_upper_L"},
                        {"leg_upper_L", "leg_lower_L"},
                        {"leg_lower_L", "ankle_L"},
                        {"pelvis", "leg_upper_R"},
                        {"leg_upper_R", "leg_lower_R"},
                        {"leg_lower_R", "ankle_R"}
    };
}

